# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Jeppe Ernst"
description:        "🦄 CODE & stuff™"
repository:        "ern-st/ern-st.github.io"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//jeppe.ernst.link"
author:             "@ern_st"
twitter:
  username:         "@ern_st"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:title/

# Markdown
markdown:           kramdown
highlighter:        rouge

# Navigation
nav:
  - name:           "About"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
  - jemoji